name: Sparkler Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13.0.1
      - name: Build with SBT
        working-directory: ./sparkler-core
        run: sbt clean package test
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Sparkler Main Container
        uses: docker/build-push-action@v2
        with:
          tags: uscdatascience/sparkler:latest
          file: sparkler-core/sparkler-deployment/docker/Dockerfile
          context: ./sparkler-core
          push: true
      - name: Build Sparkler Standalone Container
        uses: docker/build-push-action@v2
        with:
          tags: uscdatascience/sparkler-standalone:latest
          file: sparkler-core/sparkler-deployment/docker-k8s/Dockerfile
          context: ./sparkler-core
          push: true
      - name: Build Sparkler Solr Container
        uses: docker/build-push-action@v2
        with:
          tags: uscdatascience/sparkler-solr:latest
          file: sparkler-core/sparkler-deployment/docker/Dockerfile.solr
          context: ./sparkler-core
          push: true

  build-sce:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Sparkler Main Container
        uses: docker/build-push-action@v2
        with:
          tags: uscdatascience/sce-domain-discovery:latest
          file: sparkler-sce/deployment/Dockerfile
          context: ./sparkler-sce
          push: true

  build-sce-ui:
    runs-on: ubuntu-latest
    needs: build-sce
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Sparkler Main Container
        uses: docker/build-push-action@v2
        with:
          tags: uscdatascience/sparkler-ui:latest
          file: sparkler-ui/Dockerfile
          context: ./sparkler-ui
          push: true

